### web
server:
  port: 30635
  servlet:
    context-path: /xxl-job-admin
    session:
      cookie:
        http-only: true
        max-age: ${spring.mvc.interceptors.login.cookie-max-age-sec}
        secure: false
        same-site: strict
        path: /
        name: xxl-job-admin-sid
      timeout: 30m

### actuator
management:
  endpoints:
    web:
      base-path: /actuator
  health:
    mail:
      enabled: false

### resources
spring:
  application:
    name: xxl-job-admin
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    enabled: true
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
    interceptors:
      mdc:
        enabled: true
      resource-handler-registry:
        entries:
          - handlers: /hbq969-common/**
            locations: classpath:/static/hbq969-common/
          - handlers: /hbq969-dict/**
            locations: classpath:/static/hbq969-dict/
          - handlers: /hbq969-tabula/**
            locations: classpath:/static/hbq969-tabula/
          - handlers: /hbq969-sm/**
            locations: classpath:/static/hbq969-sm/
          - handlers: /xxl-job-ui/**
            locations: classpath:/static/xxl-job-ui/
          - handlers: /**
            locations:
              - classpath:/static/
              - classpath:/
        enabled: true
      login:
        enabled: true
        cookie-max-age-sec: 1800
        include-urls:
          - "/**"
        exclude-urls:
          - "/**/*.js"
          - "/**/*.css"
          - "/**/*.png"
          - "/**/*.jpg"
          - "/**/*.map"
          - "/**/*.ico"
          - "/**/error"
          - "/**/error"
          - "/common/health"
          - "/hbq969-sm/index.html"
          - "/hbq969-sm/**/login"
          - "/hbq969-sm/i18n/lang"
          - "/hbq969-sm/i18n/lang/data"
          - "/hbq969-sm/**/getPublicKey"
        session-key: xxl-job-admin-sid
        sm-initial-script:
          language: zh-CN
          charset: utf-8
        menu:
          prefix: ""
        auth:
          base:
            enabled: true
        main-layout: main_left
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      enabled: true
      base-packages: com.github.hbq969,com.xxl.job
      default-lookup-key: hikari
    hikari:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=15000
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: dbc
      password: 123456
#      jdbc-url: jdbc:postgresql://localhost:5432/xxl_job
#      driver-class-name: org.postgresql.Driver
#      username: admin
#      password: 123456
      maximum-pool-size: 10
      minimum-idle: 2
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  mail:
    host: smtp.qq.com
    port: 25
    username: xxx@qq.com
    from: xxx@qq.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

### mybatis
mybatis:
  mapper-locations:
    - classpath*:mapper/*Mapper.xml
    - classpath*:mapper/mysql/*Mapper.xml
    - classpath*:com/github/hbq969/code/**/mapper/common/*Mapper.xml
    - classpath*:com/github/hbq969/code/**/mapper/mysql/*Mapper.xml
  config-location: classpath:jpaConfig-mysql.xml
mybatis-plus:
  mapper-locations: ${mybatis.mapper-locations}
  config-location: ${mybatis.config-location}

eureka:
  instance:
    instance-id: ${eureka.instance.ip-address}:${server.port}
    ip-address: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:30140/eureka/
    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 10
    enabled: false

swagger:
  base-package: com
  api-info:
    title: xxl-job Restful API
    description: xxl-job Restful API
    termsOfService: http://127.0.0.1:${server.port}

dict:
  enabled: true
  reload:
    cron: 0 */30 * * * *
  map-key-prefix: fmt

encrypt:
  config:
    enabled: true
  restful:
    enabled: true
    aes:
      charset: utf-8
      show-log: true
      key: E793C71D5EAB4385
      iv: 8AE506C91AFB4AAC
    rsa:
      charset: utf-8
      show-log: true
      public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCe7L2gjYAmFCW8Q8S5kW7F064t/np+sP84PKLRsuZho3TZIjryGSyq8reNTm2Zrz0pKzddR0Rh6wUzP9xSAsQXH0uC6J5/WbmFhFW0k8zgkXSKktirs2BDuObEYZwJLng41yhP694H9sVBVhyqzy90Qx/dJWWa2vXHp2I+jlLELQIDAQAB
      private-key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJ7svaCNgCYUJbxDxLmRbsXTri3+en6w/zg8otGy5mGjdNkiOvIZLKryt41ObZmvPSkrN11HRGHrBTM/3FICxBcfS4Lonn9ZuYWEVbSTzOCRdIqS2KuzYEO45sRhnAkueDjXKE/r3gf2xUFWHKrPL3RDH90lZZra9cenYj6OUsQtAgMBAAECgYAvY3xv4YGy2RMffj2s79bOGn63rEgueuy/giUyzluwBaOUE4bsJeGR3+onspkv2HcuTXqmz9duMzxLueEiezypBU1UHv6PTSTWqEQUQ6eNZDwPgD1AbX7U1uTreG6lRezkhAE4X5RvuXqBgxMUeO4FVPOKCzX7e6Kp/i/UDkp56QJBAPo3Tnjm7V1RsmvjOji0OeEnv3MItcS4rEuvkTLVxKYwvmyqCQaHdCXkVsDcqrPI11neFk+KUBOzoPlfOa8b218CQQCimTQXcL9yYdqFli579Bak25Y4+w0H5RrMAqNTvbr5l4ofzPNVaT2r6Eqwpb2p7Bkw7b2GSXQ0nX01BcsFVBfzAkEAx6iwNmtWxts0+0ADKlItyUtVSm6N1J7j5TUAMMdBNre4i68Wqp4VgVL2IskycWl25eAAf5HHmiEA91wUBHW/EwJAO0+rQsmr7CtprMUFm82D3QsElzBspm6aAcUMkuVoqNbwWX1HXeaPyn9nj1xF/Q/UeJagRbXRn8e6/nZogj8UpQJAJS9dCro6Mtl9ROwdob3aOhQg3J1/whtoO/815oh3ST5P6ZtIICE64cZGpwU1ZC9RW8bdnaZ+wmp1f+qAkF1whA==
    advice-packages:
      - com.github.hbq969.code
      - com.xxl.job.admin


### xxl-job
xxl:
  job:
    accessToken: 0CF7D9D21B7C4BA7
    timeout: 3
    i18n: zh_CN
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30
  sso:
    token:
      key: xxl_job_login_token
      timeout: 604800000
    client:
      excluded:
        paths: ""
      login:
        path: /auth/login

xxl-sso:
  token:
    key: xxl_job_login_token
    timeout: 604800000
  client:
    excluded:
      paths: ""
    login:
      path: /auth/login

advice:
  log:
    enabled: false
  ex:
    enabled: true
